# Generated by Django 4.2.16 on 2024-11-23 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chatpdf", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="UploadedPDF",
        ),
    ]
