# Generated by Django 4.2.16 on 2024-12-01 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chatpdf", "0003_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="QuestionAnswer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pdf_name", models.CharField(max_length=255)),
                ("question", models.TextField()),
                ("answer", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
